nr_files = 10

rule all:
    input:
        "data/seq.tar",
        "data/seq.zip",
        "data/seq_labels.csv",
        "data/seq_files.txt",
        directory("data/dataset/")

rule create_text:
    output:
        expand('data/texts/text_{idx}.txt', idx=[f'{i:06d}' for i in range(1, nr_files + 1)]),
        "data/seq_files.txt"
    run:
        shell('''
        mkdir -p data/texts
        rm -f data/seq_files.txt
        for i in $(seq -w 000001 {nr_files})
        do
            ./create_text_data.py  --output data/texts/text_$i.txt
            echo "data/texts/text_$i.txt" >> data/seq_files.txt
        done''')

rule create_labels:
    input:
        expand('data/texts/text_{idx}.txt', idx=[f'{i:06d}' for i in range(1, nr_files + 1)])
    output:
        "data/seq_labels.csv"
    shell:
        './create_labels.py "data/texts/*"  --types int:2 str:10  -o data/seq_labels.csv'

rule create_tar:
    input:
        expand('data/texts/text_{idx}.txt', idx=[f'{i:06d}' for i in range(1, nr_files + 1)])
    output:
        "data/seq.tar"
    shell:
        "tar -cf {output} {input}"

rule create_zip:
    input:
        expand('data/texts/text_{idx}.txt', idx=[f'{i:06d}' for i in range(1, nr_files + 1)])
    output:
        "data/seq.zip"
    shell:
        "zip -q -j {output} {input}"

rule create_hugging_face_dataset:
    input:
        expand('data/texts/text_{idx}.txt', idx=[f'{i:06d}' for i in range(1, nr_files + 1)]),
        "data/seq_labels.csv"
    output:
        directory("data/dataset/")
    shell:
        './concat_txt_to_dataset.py "data/texts/*.txt" data/seq_labels.csv data/dataset/'
